[package]
name = "vim-markdownizer"
version = "0.1.0"
authors = ["Henri Bourcereau <hbourcereau@atixnet.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neovim-lib = "0.6.1"

[dependencies.markdownizer]
path = "../markdownizer"
